#--        MEILER         --#
#-- simple testing script --#
#--        v0.2.2         --#
#--                       --#
#--     programmed by     --#
#--   Klaus Rettinghaus   --#
#--                       --#
rm tests.log
rm README.md
echo running tests
echo "# MEILER TESTS" >> README.md
echo "This is an autogenerated overview of the testfiles." >> README.md
find . -type f -name "*.mei"|while read file;
do
  fname=$(basename "$file")
  saxonb-xslt -s:$file -xsl:../mei2ly.xsl -o:${file%.mei}.ly && lilypond -dno-print-pages -dpreview --formats=png --loglevel=BASIC_PROGRESS ${file%.mei}.ly >> tests.log 2>&1
  #-- next line for SVG output
  #-- saxonb-xslt -s:$file -xsl:../mei2ly.xsl LilyPondVersion="2.18.2" -o:${file%.mei}.ly && lilypond -dbackend=svg -dno-print-pages -dpreview --loglevel=BASIC_PROGRESS ${file%.mei}.ly >> tests.log 2>&1
  #-- rm ${file%.mei}.ly

  #-- add output to README.md
  echo "### [$fname]($fname)" >> README.md
  echo "![$fname](${fname%.mei}.preview.png)" >> README.md
done
echo done
echo see tests.log for details
