#--        MEILER         --#
#-- simple testing script --#
#--        v0.2.6         --#
#--                       --#
#--     programmed by     --#
#--   Klaus Rettinghaus   --#
#--                       --#
rm tests.log
rm README.md
echo running tests
echo "# MEILER TESTS" >> README.md
echo "This is an autogenerated overview of the testfiles." >> README.md
find . -type f -name "*.mei"|while read file;
do
  fname=$(basename "$file")
  saxonb-xslt -s:$file -o:${file%.mei}.ly -xsl:../mei2ly.xsl LilyPondVersion="2.18.2" && lilypond -dno-print-pages -dpreview --formats=png --loglevel=BASIC_PROGRESS ${file%.mei}.ly >> tests.log 2>&1
  #-- next line for SVG output
  saxonb-xslt -s:$file -o:${file%.mei}.ly -xsl:../mei2ly.xsl useSvgBackend=true forceLayout=true && lilypond -dno-print-pages -dno-point-and-click -dbackend=svg -dpreview --loglevel=BASIC_PROGRESS ${file%.mei}.ly >> tests.log 2>&1
  rm ${file%.mei}.ly

  #-- add output to README.md
  echo "### [$fname]($fname)" >> README.md
  echo "![$fname](${fname%.mei}.preview.png)" >> README.md
done
echo "" >> README.md
echo "All test files are licensed under a [Creative Commons Attribution 4.0 International License](http://creativecommons.org/licenses/by/4.0/)." >> README.md
echo done
echo see tests.log for details
